[tools]
rojo = "rojo-rbx/rojo@7.4.4"
darklua = "seaofvoices/darklua@0.15.0"
stylua = "johnnymorganz/stylua@2.0.2"
selene = "kampfkarren/selene@0.27.1"
luau-lsp = "johnnymorganz/luau-lsp@1.38.0"
wally = "upliftgames/wally@0.3.2"
wally-package-types = "johnnymorganz/wally-package-types@1.4.1"
