# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

# Ensure this are up to date for any new project

[tools]
rojo = "rojo-rbx/rojo@7.5.1"
darklua = "seaofvoices/darklua@0.16.0"
stylua = "johnnymorganz/stylua@2.1.0"
selene = "kampfkarren/selene@0.29.0"
luau-lsp = "johnnymorganz/luau-lsp@1.52.1"
wally = "upliftgames/wally@0.3.2"
wally-package-types = "johnnymorganz/wally-package-types@1.5.1"
lune = "lune-org/lune@0.9.4"
