[package]
name = "finn/project-template"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Fusion = "elttob/fusion@0.3.0"
Observers = "sleitnick/observers@0.3.4"
Promise = "evaera/promise@4.0.0"
Promise = "howmanysmall/typed-promise@4.0.6"
Trove = "sleitnick/trove@1.5.1"
Signal = "sleitnick/signal@2.0.3"
Rodux = "roblox/rodux@3.0.0"
Tree = "sleitnick/tree@1.1.0"
Comm = "sleitnick/comm@1.0.1"
Loader = "sleitnick/loader@2.0.0"
Rodux = "roblox/rodux@3.0.0"

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@1.0.3"